platform :ios, '12.0'
inhibit_all_warnings!

target 'CoreMLImageClassification' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'SnapKit'
  pod 'Skafos', '~> 4.0.2'
end

